apiVersion: v1
kind: Service
metadata:
  name: tekton-tutorial
  labels:
    app: tekton-tutorial
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tekton-tutorial
  type: NodePort
